DELETE FROM public.airport;
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Abu Dhabi International Airport', 'AE', 'Abu Dhabi', 'AUH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Dubai International Airport', 'AE', 'Dubai', 'DXB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Al Maktoum International Airport', 'AE', 'Jebel Ali', 'DWC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sharjah International Airport', 'AE', 'Sharjah', 'SHJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tirana International Airport Mother Teresa', 'AL', 'Tirana', 'TIA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Zvartnots International Airport', 'AM', 'Yerevan', 'EVN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Quatro de Fevereiro International Airport', 'AO', 'Luanda', 'LAD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Jorge Newbery Airpark', 'AR', 'Buenos Aires', 'AEP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Minister Pistarini International Airport', 'AR', 'Buenos Aires (Ezeiza)', 'EZE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Vienna International Airport', 'AT', 'Vienna', 'VIE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Adelaide International Airport', 'AU', 'Adelaide', 'ADL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Brisbane International Airport', 'AU', 'Brisbane', 'BNE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Darwin International Airport / RAAF Darwin', 'AU', 'Darwin', 'DRW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Melbourne International Airport', 'AU', 'Melbourne', 'MEL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Perth International Airport', 'AU', 'Perth', 'PER');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sydney Kingsford Smith International Airport', 'AU', 'Sydney', 'SYD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Queen Beatrix International Airport', 'AW', 'Oranjestad', 'AUA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Heydar Aliyev International Airport', 'AZ', 'Baku', 'GYD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hazrat Shahjalal International Airport', 'BD', 'Dhaka', 'DAC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Brussels Airport', 'BE', 'Zaventem', 'BRU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Burgas Airport', 'BG', 'Burgas', 'BOJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sofia Airport', 'BG', 'Sofia', 'SOF');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Varna Airport', 'BG', 'Varna', 'VAR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Bahrain International Airport', 'BH', 'Manama', 'BAH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Brunei International Airport', 'BN', 'Bandar Seri Begawan', 'BWN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Viru Viru International Airport', 'BO', 'Santa Cruz', 'VVI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Flamingo International Airport', 'BQ', 'Kralendijk, Bonaire', 'BON');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Val de Cans/Júlio Cezar Ribeiro International Airport', 'BR', 'Belém', 'BEL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tancredo Neves International Airport', 'BR', 'Belo Horizonte', 'CNF');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Presidente Juscelino Kubitschek International Airport', 'BR', 'Brasília', 'BSB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hercílio Luz International Airport', 'BR', 'Florianópolis', 'FLN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Eduardo Gomes International Airport', 'BR', 'Manaus', 'MAO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Porto Seguro Airport', 'BR', 'Porto Seguro', 'BPS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Rio Galeão – Tom Jobim International Airport', 'BR', 'Rio De Janeiro', 'GIG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Deputado Luiz Eduardo Magalhães International Airport', 'BR', 'Salvador', 'SSA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Guarulhos - Governador André Franco Montoro International Airport', 'BR', 'São Paulo', 'GRU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Eurico de Aguiar Salles Airport', 'BR', 'Vitória', 'VIX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Lynden Pindling International Airport', 'BS', 'Nassau', 'NAS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sir Seretse Khama International Airport', 'BW', 'Gaborone', 'GBE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Minsk National Airport', 'BY', 'Minsk', 'MSQ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Philip S. W. Goldson International Airport', 'BZ', 'Belize City', 'BZE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'London Airport', 'CA', 'Abbotsford', 'YXX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Calgary International Airport', 'CA', 'Calgary', 'YYC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Edmonton International Airport', 'CA', 'Edmonton', 'YEG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Halifax / Stanfield International Airport', 'CA', 'Halifax', 'YHZ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Montreal / Pierre Elliott Trudeau International Airport', 'CA', 'Montréal', 'YUL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ottawa Macdonald-Cartier International Airport', 'CA', 'Ottawa', 'YOW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Prince George Airport', 'CA', 'Prince George', 'YXS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Quebec Jean Lesage International Airport', 'CA', 'Quebec', 'YQB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'St. John''s International Airport', 'CA', 'St. John''s', 'YYT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Toronto Lester B. Pearson International Airport', 'CA', 'Toronto', 'YYZ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Vancouver International Airport', 'CA', 'Vancouver', 'YVR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Victoria International Airport', 'CA', 'Victoria', 'YYJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Winnipeg / James Armstrong Richardson International Airport', 'CA', 'Winnipeg', 'YWG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ndjili International Airport', 'CD', 'Kinshasa', 'FIH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Geneva Cointrin International Airport', 'CH', 'Geneva', 'GVA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Zürich Airport', 'CH', 'Zurich', 'ZRH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Comodoro Arturo Merino Benítez International Airport', 'CL', 'Santiago', 'SCL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Beijing Capital International Airport', 'CN', 'Beijing', 'PEK');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Beijing Daxing International Airport', 'CN', 'Beijing', 'PKX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Changchun Longjia International Airport', 'CN', 'Changchun', 'CGQ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Changsha Huanghua International Airport', 'CN', 'Changsha (Changsha)', 'CSX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Chengdu Tianfu International Airport', 'CN', 'Chengdu (Jianyang)', 'TFU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Chengdu Shuangliu International Airport', 'CN', 'Chengdu (Shuangliu)', 'CTU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Chongqing Jiangbei International Airport', 'CN', 'Chongqing', 'CKG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ezhou Huahu Airport', 'CN', 'Ezhou', 'EHU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Fuzhou Changle International Airport', 'CN', 'Fuzhou', 'FOC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Dalian Zhoushuizi International Airport', 'CN', 'Ganjingzi, Dalian', 'DLC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Guangzhou Baiyun International Airport', 'CN', 'Guangzhou (Huadu)', 'CAN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Guilin Liangjiang International Airport', 'CN', 'Guilin (Lingui)', 'KWL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Guiyang Longdongbao International Airport', 'CN', 'Guiyang (Nanming)', 'KWE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Haikou Meilan International Airport', 'CN', 'Haikou (Meilan)', 'HAK');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hangzhou Xiaoshan International Airport', 'CN', 'Hangzhou', 'HGH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Harbin Taiping International Airport', 'CN', 'Harbin', 'HRB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hohhot Baita International Airport', 'CN', 'Hohhot', 'HET');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Shenyang Taoxian International Airport', 'CN', 'Hunnan, Shenyang', 'SHE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Qingdao Jiaodong International Airport', 'CN', 'Jiaozhou, Qingdao', 'TAO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Jinan Yaoqiang International Airport', 'CN', 'Jinan', 'TNA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kunming Changshui International Airport', 'CN', 'Kunming', 'KMG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Lanzhou Zhongchuan International Airport', 'CN', 'Lanzhou (Yongdeng)', 'LHW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Nanchang Changbei International Airport', 'CN', 'Nanchang', 'KHN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Nanjing Lukou International Airport', 'CN', 'Nanjing', 'NKG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Nanning Wuxu Airport', 'CN', 'Nanning (Jiangnan)', 'NNG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ningbo Lishe International Airport', 'CN', 'Ningbo', 'NGB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sanya Phoenix International Airport', 'CN', 'Sanya (Tianya)', 'SYX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Shanghai Hongqiao International Airport', 'CN', 'Shanghai (Minhang)', 'SHA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Shanghai Pudong International Airport', 'CN', 'Shanghai (Pudong)', 'PVG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Shenzhen Bao''an International Airport', 'CN', 'Shenzhen (Bao''an)', 'SZX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Taiyuan Wusu Airport', 'CN', 'Taiyuan', 'TYN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tianjin Binhai International Airport', 'CN', 'Tianjin', 'TSN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ürümqi Diwopu International Airport', 'CN', 'Ürümqi', 'URC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Wenzhou Longwan International Airport', 'CN', 'Wenzhou', 'WNZ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Wuhan Tianhe International Airport', 'CN', 'Wuhan (Huangpi)', 'WUH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Xiamen Gaoqi International Airport', 'CN', 'Xiamen', 'XMN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Xi''an Xianyang International Airport', 'CN', 'Xianyang (Weicheng)', 'XIY');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Yantai Penglai International Airport', 'CN', 'Yantai', 'YNT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Zhengzhou Xinzheng International Airport', 'CN', 'Zhengzhou', 'CGO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'El Dorado International Airport', 'CO', 'Bogota', 'BOG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Guanacaste Airport', 'CR', 'Liberia', 'LIR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'José Martí International Airport', 'CU', 'Havana', 'HAV');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Juan Gualberto Gomez International Airport', 'CU', 'Matanzas', 'VRA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Amílcar Cabral International Airport', 'CV', 'Espargos', 'SID');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hato International Airport', 'CW', 'Willemstad', 'CUR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Larnaca International Airport', 'CY', 'Larnaca', 'LCA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Václav Havel Airport Prague', 'CZ', 'Prague', 'PRG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Berlin Brandenburg Airport', 'DE', 'Berlin', 'BER');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Düsseldorf Airport', 'DE', 'Düsseldorf', 'DUS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Frankfurt Airport', 'DE', 'Frankfurt am Main', 'FRA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hamburg Helmut Schmidt Airport', 'DE', 'Hamburg', 'HAM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hannover Airport', 'DE', 'Hannover', 'HAJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Cologne Bonn Airport', 'DE', 'Köln (Cologne)', 'CGN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Munich Airport', 'DE', 'Munich', 'MUC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Nuremberg Airport', 'DE', 'Nuremberg', 'NUE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Leipzig/Halle Airport', 'DE', 'Schkeuditz', 'LEJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Stuttgart Airport', 'DE', 'Stuttgart', 'STR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Djibouti-Ambouli Airport', 'DJ', 'Djibouti City', 'JIB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Billund Airport', 'DK', 'Billund', 'BLL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Copenhagen Kastrup Airport', 'DK', 'Copenhagen', 'CPH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Punta Cana International Airport', 'DO', 'Punta Cana', 'PUJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Las Américas International Airport', 'DO', 'Santo Domingo', 'SDQ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Houari Boumediene Airport', 'DZ', 'Algiers', 'ALG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'José Joaquín de Olmedo International Airport', 'EC', 'Guayaquil', 'GYE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Mariscal Sucre International Airport', 'EC', 'Quito', 'UIO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Lennart Meri Tallinn Airport', 'EE', 'Tallinn', 'TLL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Cairo International Airport', 'EG', 'Cairo', 'CAI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hurghada International Airport', 'EG', 'Hurghada', 'HRG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sharm El Sheikh International Airport', 'EG', 'Sharm El Sheikh', 'SSH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Alicante-Elche Miguel Hernández Airport', 'ES', 'Alicante', 'ALC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Josep Tarradellas Barcelona-El Prat Airport', 'ES', 'Barcelona', 'BCN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Fuerteventura Airport', 'ES', 'El Matorral', 'FUE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Gran Canaria Airport', 'ES', 'Gran Canaria Island', 'LPA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ibiza Airport', 'ES', 'Ibiza (Eivissa)', 'IBZ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Adolfo Suárez Madrid–Barajas Airport', 'ES', 'Madrid', 'MAD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Málaga-Costa del Sol Airport', 'ES', 'Málaga', 'AGP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Palma de Mallorca Airport', 'ES', 'Palma de Mallorca', 'PMI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'César Manrique-Lanzarote Airport', 'ES', 'San Bartolomé', 'ACE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Santiago-Rosalía de Castro Airport', 'ES', 'Santiago de Compostela', 'SCQ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tenerife Sur Airport', 'ES', 'Tenerife', 'TFS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Addis Ababa Bole International Airport', 'ET', 'Addis Ababa', 'ADD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Helsinki Vantaa Airport', 'FI', 'Helsinki', 'HEL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Bordeaux-Mérignac Airport', 'FR', 'Bordeaux/Mérignac', 'BOD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Lyon Saint-Exupéry Airport', 'FR', 'Lyon', 'LYS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Marseille Provence Airport', 'FR', 'Marseille', 'MRS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Nice-Côte d''Azur Airport', 'FR', 'Nice', 'NCE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Charles de Gaulle International Airport', 'FR', 'Paris', 'CDG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Paris-Orly Airport', 'FR', 'Paris', 'ORY');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'EuroAirport Basel-Mulhouse-Freiburg', 'FR', 'Saint-Louis', 'BSL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Toulouse-Blagnac Airport', 'FR', 'Toulouse/Blagnac', 'TLS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Belfast International Airport', 'GB', 'Belfast', 'BFS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Birmingham International Airport', 'GB', 'Birmingham', 'BHX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Edinburgh Airport', 'GB', 'Edinburgh', 'EDI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'London Gatwick Airport', 'GB', 'London', 'LGW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'London Heathrow Airport', 'GB', 'London', 'LHR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'London Luton Airport', 'GB', 'London', 'LTN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'London Stansted Airport', 'GB', 'London', 'STN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Manchester Airport', 'GB', 'Manchester', 'MAN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Glasgow International Airport', 'GB', 'Paisley, Renfrewshire', 'GLA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tbilisi International Airport', 'GE', 'Tbilisi', 'TBS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Cayenne – Félix Eboué Airport', 'GF', 'Matoury', 'CAY');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kotoka International Airport', 'GH', 'Accra', 'ACC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Banjul International Airport', 'GM', 'Banjul', 'BJL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Pointe-à-Pitre Le Raizet International  Airport', 'GP', 'Pointe-à-Pitre', 'PTP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Athens Eleftherios Venizelos International Airport', 'GR', 'Athens', 'ATH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Heraklion International Nikos Kazantzakis Airport', 'GR', 'Heraklion', 'HER');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Thessaloniki Macedonia International Airport', 'GR', 'Thessaloniki', 'SKG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'La Aurora Airport', 'GT', 'Guatemala City', 'GUA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Antonio B. Won Pat International Airport', 'GU', 'Hagåtña', 'GUM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hong Kong International Airport', 'HK', 'Islands', 'HKG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Zagreb Airport', 'HR', 'Zagreb', 'ZAG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Toussaint Louverture International Airport', 'HT', 'Port-au-Prince', 'PAP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Budapest Liszt Ferenc International Airport', 'HU', 'Budapest', 'BUD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sultan Aji Muhammad Sulaiman Sepinggan International Airport', 'ID', 'Balikpapan', 'BPN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ngurah Rai (Bali) International Airport', 'ID', 'Denpasar', 'DPS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Soekarno-Hatta International Airport', 'ID', 'Jakarta', 'CGK');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kualanamu International Airport', 'ID', 'Medan', 'KNO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Dortheys Hiyo Eluay International Airport', 'ID', 'Sentani', 'DJJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Juanda International Airport', 'ID', 'Surabaya', 'SUB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hasanuddin International Airport', 'ID', 'Ujung Pandang', 'UPG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Dublin Airport', 'IE', 'Dublin', 'DUB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Shannon Airport', 'IE', 'Shannon', 'SNN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ramon International Airport', 'IL', 'Eilat', 'ETM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ben Gurion International Airport', 'IL', 'Tel Aviv', 'TLV');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kempegowda International Airport', 'IN', 'Bangalore', 'BLR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Chennai International Airport', 'IN', 'Chennai', 'MAA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Rajiv Gandhi International Airport', 'IN', 'Hyderabad', 'HYD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Cochin International Airport', 'IN', 'Kochi', 'COK');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Netaji Subhash Chandra Bose International Airport', 'IN', 'Kolkata', 'CCU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Chhatrapati Shivaji International Airport', 'IN', 'Mumbai', 'BOM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Indira Gandhi International Airport', 'IN', 'New Delhi', 'DEL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Rajkot International Airport', 'IN', 'Rajkot', 'HSR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Thiruvananthapuram International Airport', 'IN', 'Thiruvananthapuram', 'TRV');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Dabolim Airport', 'IN', 'Vasco da Gama', 'GOI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Baghdad International Airport / New Al Muthana Air Base', 'IQ', 'Baghdad', 'BGW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Mashhad International Airport', 'IR', 'Mashhad', 'MHD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Shiraz Shahid Dastghaib International Airport', 'IR', 'Shiraz', 'SYZ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Imam Khomeini International Airport', 'IR', 'Tehran', 'IKA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Mehrabad International Airport', 'IR', 'Tehran', 'THR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Keflavik International Airport', 'IS', 'Reykjavík', 'KEF');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Bari Karol Wojtyła Airport', 'IT', 'Bari', 'BRI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Bologna Guglielmo Marconi Airport', 'IT', 'Bologna', 'BLQ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Brindisi Airport', 'IT', 'Brindisi', 'BDS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Cagliari Elmas Airport', 'IT', 'Cagliari', 'CAG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Catania-Fontanarossa Airport', 'IT', 'Catania', 'CTA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Milan Bergamo Airport', 'IT', 'Milan', 'BGY');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Malpensa International Airport', 'IT', 'Milan', 'MXP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Naples International Airport', 'IT', 'Napoli', 'NAP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Falcone–Borsellino Airport', 'IT', 'Palermo', 'PMO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Pisa International Airport', 'IT', 'Pisa', 'PSA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Rome–Fiumicino Leonardo da Vinci International Airport', 'IT', 'Rome', 'FCO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Turin Airport', 'IT', 'Torino', 'TRN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Venice Marco Polo Airport', 'IT', 'Venice', 'VCE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Verona-Villafranca Valerio Catullo Airport', 'IT', 'Villafranca di Verona', 'VRN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Norman Manley International Airport', 'JM', 'Kingston', 'KIN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Queen Alia International Airport', 'JO', 'Amman', 'AMM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Fukuoka Airport', 'JP', 'Fukuoka', 'FUK');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Yokota Air Base', 'JP', 'Fussa', 'OKO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kagoshima Airport', 'JP', 'Kagoshima', 'KOJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Naha Airport / JASDF Naha Air Base', 'JP', 'Naha', 'OKA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Narita International Airport', 'JP', 'Narita', 'NRT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sendai Airport', 'JP', 'Natori', 'SDJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Osaka International Airport', 'JP', 'Osaka', 'ITM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kansai International Airport', 'JP', 'Osaka', 'KIX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'New Chitose Airport', 'JP', 'Sapporo', 'CTS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Chubu Centrair International Airport', 'JP', 'Tokoname', 'NGO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tokyo Haneda International Airport', 'JP', 'Tokyo', 'HND');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Moi International Airport', 'KE', 'Mombasa', 'MBA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Jomo Kenyatta International Airport', 'KE', 'Nairobi', 'NBO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Manas International Airport', 'KG', 'Bishkek', 'FRU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Phnom Penh International Airport', 'KH', 'Phnom Penh (Pou Senchey)', 'PNH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Siem Reap International Airport', 'KH', 'Siem Reap', 'REP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Siem Reap-Angkor International Airport', 'KH', 'Siem Reap', 'SAI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Gimhae International Airport', 'KR', 'Busan', 'PUS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Jeju International Airport', 'KR', 'Jeju City', 'CJU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Muan International Airport', 'KR', 'Piseo-ri (Muan)', 'MWX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Gimpo International Airport', 'KR', 'Seoul', 'GMP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Incheon International Airport', 'KR', 'Seoul', 'ICN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kuwait International Airport', 'KW', 'Kuwait City', 'KWI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Owen Roberts International Airport', 'KY', 'George Town', 'GCM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Almaty International Airport', 'KZ', 'Almaty', 'ALA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Nursultan Nazarbayev International Airport', 'KZ', 'Nur-Sultan', 'NQZ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Beirut Rafic Hariri International Airport', 'LB', 'Beirut', 'BEY');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hewanorra International Airport', 'LC', 'Vieux Fort', 'UVF');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Bandaranaike International Colombo Airport', 'LK', 'Colombo', 'CMB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Roberts International Airport', 'LR', 'Monrovia', 'ROB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Vilnius International Airport', 'LT', 'Vilnius', 'VNO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Luxembourg-Findel International Airport', 'LU', 'Luxembourg', 'LUX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Riga International Airport', 'LV', 'Riga', 'RIX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Mitiga International Airport', 'LY', 'Tripoli', 'MJI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Mohammed V International Airport', 'MA', 'Casablanca', 'CMN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Podgorica Airport / Podgorica Golubovci Airbase', 'ME', 'Podgorica', 'TGD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ivato Airport', 'MG', 'Antananarivo', 'TNR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Skopje International Airport', 'MK', 'Ilinden', 'SKP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Modibo Keita International Airport', 'ML', 'Bamako', 'BKO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Mandalay International Airport', 'MM', 'Mandalay', 'MDL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Yangon International Airport', 'MM', 'Yangon', 'RGN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ulaanbaatar Chinggis Khaan International Airport', 'MN', 'Ulaanbaatar (Sergelen)', 'UBN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Macau International Airport', 'MO', 'Nossa Senhora do Carmo', 'MFM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Martinique Aimé Césaire International Airport', 'MQ', 'Fort-de-France', 'FDF');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Nouakchott–Oumtounsy International Airport', 'MR', 'Nouakchott', 'NKC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Malta International Airport', 'MT', 'Valletta', 'MLA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sir Seewoosagur Ramgoolam International Airport', 'MU', 'Plaine Magnien', 'MRU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Malé International Airport', 'MV', 'Malé', 'MLE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Juan N. Álvarez', 'MX', 'Ciudad de Acapulco', 'ACA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Gral. Mariano Escobedo', 'MX', 'Ciudad de Apodaca', 'MTY');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional de Cancún', 'MX', 'Ciudad de Cancún', 'CUN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional de Cozumel', 'MX', 'Ciudad de Cozumel', 'CZM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Gral, Guadalupe Victoria', 'MX', 'Ciudad de Durango', 'DGO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Gral. Rafael Buelna', 'MX', 'Ciudad de Mazatlàn', 'MZT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Manuel Crescencio Rejón', 'MX', 'Ciudad de Mérida', 'MID');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Lic. Benito Juárez', 'MX', 'Ciudad de México', 'MEX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Lic. Gustavo Díaz Ordaz', 'MX', 'Ciudad de Puerto Vallarta', 'PVR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional de Los Cabos', 'MX', 'Ciudad de San José del Cabo', 'SJD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Del Bajío', 'MX', 'Ciudad de Silao', 'BJX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Gral. Abelardo Rodriguez', 'MX', 'Ciudad de Tijuana', 'TIJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Miguel Hidalgo', 'MX', 'Ciudad de Tlajomulco de Zúñiga', 'GDL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Adolfo López Mateos', 'MX', 'Ciudad de Toluca', 'TLC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'General Ignacio P. Garcia International Airport', 'MX', 'Hermosillo', 'HMO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional General Felipe Ángeles', 'MX', 'Mexico City', 'NLU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kuala Lumpur International Airport', 'MY', 'Sepang', 'KUL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Maputo Airport', 'MZ', 'Maputo', 'MPM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hosea Kutako International Airport', 'NA', 'Windhoek', 'WDH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Nouméa Magenta Airport', 'NC', 'Nouméa', 'GEA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Diori Hamani International Airport', 'NE', 'Niamey', 'NIM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Nnamdi Azikiwe International Airport', 'NG', 'Abuja', 'ABV');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Murtala Muhammed International Airport', 'NG', 'Lagos', 'LOS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Amsterdam Airport Schiphol', 'NL', 'Amsterdam', 'AMS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Eindhoven Airport', 'NL', 'Eindhoven', 'EIN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Bergen Airport, Flesland', 'NO', 'Bergen', 'BGO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Oslo Airport, Gardermoen', 'NO', 'Oslo', 'OSL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Stavanger Airport, Sola', 'NO', 'Stavanger', 'SVG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tromsø Airport, Langnes', 'NO', 'Tromsø', 'TOS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Trondheim Airport, Værnes', 'NO', 'Trondheim', 'TRD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tribhuvan International Airport', 'NP', 'Kathmandu', 'KTM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Auckland International Airport', 'NZ', 'Auckland', 'AKL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Christchurch International Airport', 'NZ', 'Christchurch', 'CHC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Wellington International Airport', 'NZ', 'Wellington', 'WLG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Duqm International Airport', 'OM', 'Duqm', 'DQM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Muscat International Airport', 'OM', 'Muscat', 'MCT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tocumen International Airport', 'PA', 'Tocumen', 'PTY');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Alejandro Velasco Astete International Airport', 'PE', 'Cusco', 'CUZ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Jorge Chávez International Airport', 'PE', 'Lima', 'LIM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Faa''a International Airport', 'PF', 'Papeete', 'PPT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Port Moresby Jacksons International Airport', 'PG', 'Port Moresby', 'POM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Francisco Bangoy International Airport', 'PH', 'Davao', 'DVO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Mactan Cebu International Airport', 'PH', 'Lapu-Lapu City', 'CEB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ninoy Aquino International Airport', 'PH', 'Manila', 'MNL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Islamabad International Airport', 'PK', 'Attock', 'ISB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Jinnah International Airport', 'PK', 'Karachi', 'KHI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Allama Iqbal International Airport', 'PK', 'Lahore', 'LHE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Gdańsk Lech Wałęsa Airport', 'PL', 'Gdańsk', 'GDN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kraków John Paul II International Airport', 'PL', 'Kraków', 'KRK');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Warsaw Chopin Airport', 'PL', 'Warsaw', 'WAW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Luis Munoz Marin International Airport', 'PR', 'San Juan', 'SJU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Faro Airport', 'PT', 'Faro', 'FAO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Madeira International Airport Cristiano Ronaldo', 'PT', 'Funchal', 'FNC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Humberto Delgado Airport (Lisbon Portela Airport)', 'PT', 'Lisbon', 'LIS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'João Paulo II Airport', 'PT', 'Ponta Delgada', 'PDL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Francisco de Sá Carneiro Airport', 'PT', 'Porto', 'OPO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Silvio Pettirossi', 'PY', 'Asunción', 'ASU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Guaraní', 'PY', 'Ciudad del Este', 'AGT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Dr. Luis Maria Argaña', 'PY', 'Mariscal Estigarribia', 'ESG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Aeropuerto Internacional Dr. Augusto Roberto Fuster', 'PY', 'Pedro Juan Caballero', 'PJC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hamad International Airport', 'QA', 'Doha', 'DOH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Roland Garros Airport', 'RE', 'Sainte-Marie', 'RUN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Henri Coandă International Airport', 'RO', 'Bucharest', 'OTP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Belgrade Nikola Tesla Airport', 'RS', 'Belgrade', 'BEG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Vladivostok International Airport', 'RU', 'Artyom', 'VVO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kazan International Airport', 'RU', 'Kazan', 'KZN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Krasnoyarsk International Airport', 'RU', 'Krasnoyarsk', 'KJA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Domodedovo International Airport', 'RU', 'Moscow', 'DME');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sheremetyevo International Airport', 'RU', 'Moscow', 'SVO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Vnukovo International Airport', 'RU', 'Moscow', 'VKO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Zhukovsky International Airport', 'RU', 'Moscow', 'ZIA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Novosibirsk Tolmachevo Airport', 'RU', 'Novosibirsk', 'OVB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Platov International Airport', 'RU', 'Rostov-on-Don', 'ROV');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kurumoch International Airport', 'RU', 'Samara', 'KUF');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Gagarin International Airport', 'RU', 'Saratov', 'GSV');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sochi International Airport', 'RU', 'Sochi', 'AER');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Pulkovo Airport', 'RU', 'St. Petersburg', 'LED');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ufa International Airport', 'RU', 'Ufa', 'UFA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Koltsovo Airport', 'RU', 'Yekaterinburg', 'SVX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kigali International Airport', 'RW', 'Kigali', 'KGL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'King Fahd International Airport', 'SA', 'Ad Dammam', 'DMM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'King Abdulaziz Air Base', 'SA', 'Dhahran', 'DHA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'King Abdulaziz International Airport', 'SA', 'Jeddah', 'JED');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Prince Mohammad Bin Abdulaziz Airport', 'SA', 'Medina', 'MED');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'King Khaled International Airport', 'SA', 'Riyadh', 'RUH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Honiara International Airport', 'SB', 'Honiara', 'HIR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Seychelles International Airport', 'SC', 'Mahe Island', 'SEZ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Khartoum International Airport', 'SD', 'Khartoum', 'KRT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Gothenburg-Landvetter Airport', 'SE', 'Gothenburg', 'GOT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Stockholm-Arlanda Airport', 'SE', 'Stockholm', 'ARN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Singapore Changi Airport', 'SG', 'Singapore', 'SIN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ljubljana Jože Pučnik Airport', 'SI', 'Ljubljana', 'LJU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'M. R. Štefánik Airport', 'SK', 'Bratislava', 'BTS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Lungi International Airport', 'SL', 'Freetown (Lungi-Town)', 'FNA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Blaise Diagne International Airport', 'SN', 'Dakar', 'DSS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Johan Adolf Pengel International Airport', 'SR', 'Zandery', 'PBM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Juba International Airport', 'SS', 'Juba', 'JUB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Monseñor Óscar Arnulfo Romero International Airport', 'SV', 'San Salvador (San Luis Talpa)', 'SAL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Princess Juliana International Airport', 'SX', 'Saint Martin', 'SXM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Damascus International Airport', 'SY', 'Damascus', 'DAM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'King Mswati III International Airport', 'SZ', 'Mpaka', 'SHO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Providenciales International Airport', 'TC', 'Providenciales', 'PLS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'N''Djamena International Airport', 'TD', 'N''Djamena', 'NDJ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Suvarnabhumi Airport', 'TH', 'Bangkok', 'BKK');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Don Mueang International Airport', 'TH', 'Bangkok', 'DMK');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Chiang Mai International Airport', 'TH', 'Chiang Mai', 'CNX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Phuket International Airport', 'TH', 'Phuket', 'HKT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ashgabat International Airport', 'TM', 'Ashgabat', 'ASB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tunis Carthage International Airport', 'TN', 'Tunis', 'TUN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Esenboğa International Airport', 'TR', 'Ankara', 'ESB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Antalya International Airport', 'TR', 'Antalya', 'AYT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'İstanbul Airport', 'TR', 'Arnavutköy, Istanbul', 'IST');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'İstanbul Atatürk Airport', 'TR', 'Bakırköy, Istanbul', 'ISL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Milas Bodrum International Airport', 'TR', 'Bodrum', 'BJV');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Dalaman International Airport', 'TR', 'Dalaman', 'DLM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Adnan Menderes International Airport', 'TR', 'İzmir', 'ADB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Istanbul Sabiha Gökçen International Airport', 'TR', 'Pendik, Istanbul', 'SAW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kaohsiung International Airport', 'TW', 'Kaohsiung (Xiaogang)', 'KHH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Taiwan Taoyuan International Airport', 'TW', 'Taoyuan (Dayuan)', 'TPE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Julius Nyerere International Airport', 'TZ', 'Dar es Salaam', 'DAR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Abeid Amani Karume International Airport', 'TZ', 'Zanzibar', 'ZNZ');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Boryspil International Airport', 'UA', 'Boryspil', 'KBP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Lviv International Airport', 'UA', 'Lviv', 'LWO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Entebbe International Airport', 'UG', 'Kampala', 'EBB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ted Stevens Anchorage International Airport', 'US', 'Anchorage', 'ANC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Hartsfield Jackson Atlanta International Airport', 'US', 'Atlanta', 'ATL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Austin Bergstrom International Airport', 'US', 'Austin', 'AUS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Baltimore/Washington International Thurgood Marshall Airport', 'US', 'Baltimore', 'BWI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Logan International Airport', 'US', 'Boston', 'BOS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Buffalo Niagara International Airport', 'US', 'Buffalo', 'BUF');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Joint Base Andrews', 'US', 'Camp Springs', 'ADW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Charlotte Douglas International Airport', 'US', 'Charlotte', 'CLT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Chicago Midway International Airport', 'US', 'Chicago', 'MDW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Chicago O''Hare International Airport', 'US', 'Chicago', 'ORD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Cincinnati Northern Kentucky International Airport', 'US', 'Cincinnati / Covington', 'CVG');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Cleveland Hopkins International Airport', 'US', 'Cleveland', 'CLE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'John Glenn Columbus International Airport', 'US', 'Columbus', 'CMH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Dallas Fort Worth International Airport', 'US', 'Dallas-Fort Worth', 'DFW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Denver International Airport', 'US', 'Denver', 'DEN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Detroit Metropolitan Wayne County Airport', 'US', 'Detroit', 'DTW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Washington Dulles International Airport', 'US', 'Dulles', 'IAD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Fairbanks International Airport', 'US', 'Fairbanks', 'FAI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Fort Lauderdale Hollywood International Airport', 'US', 'Fort Lauderdale', 'FLL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Southwest Florida International Airport', 'US', 'Fort Myers', 'RSW');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Daniel K Inouye International Airport', 'US', 'Honolulu', 'HNL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'George Bush Intercontinental Houston Airport', 'US', 'Houston', 'IAH');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Indianapolis International Airport', 'US', 'Indianapolis', 'IND');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Jacksonville International Airport', 'US', 'Jacksonville', 'JAX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kansas City International Airport', 'US', 'Kansas City', 'MCI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Harry Reid International Airport', 'US', 'Las Vegas', 'LAS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Los Angeles / Tom Bradley International Airport', 'US', 'Los Angeles', 'LAX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Louisville Muhammad Ali International Airport', 'US', 'Louisville', 'SDF');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Memphis International Airport', 'US', 'Memphis', 'MEM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Miami International Airport', 'US', 'Miami', 'MIA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'General Mitchell International Airport', 'US', 'Milwaukee', 'MKE');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Minneapolis–Saint Paul International Airport / Wold–Chamberlain Field', 'US', 'Minneapolis', 'MSP');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Nashville International Airport', 'US', 'Nashville', 'BNA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Louis Armstrong New Orleans International Airport', 'US', 'New Orleans', 'MSY');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'John F Kennedy International Airport', 'US', 'New York', 'JFK');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'La Guardia Airport', 'US', 'New York', 'LGA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Newark Liberty International Airport', 'US', 'Newark', 'EWR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Metropolitan Oakland International Airport', 'US', 'Oakland', 'OAK');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Eppley Airfield', 'US', 'Omaha', 'OMA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ontario International Airport', 'US', 'Ontario', 'ONT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Orlando International Airport', 'US', 'Orlando', 'MCO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Orlando Sanford International Airport', 'US', 'Orlando', 'SFB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Philadelphia International Airport', 'US', 'Philadelphia', 'PHL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Phoenix Sky Harbor International Airport', 'US', 'Phoenix', 'PHX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Pittsburgh International Airport', 'US', 'Pittsburgh', 'PIT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Portland International Airport', 'US', 'Portland', 'PDX');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Portland International Jetport', 'US', 'Portland', 'PWM');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Raleigh Durham International Airport', 'US', 'Raleigh/Durham', 'RDU');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Reno Tahoe International Airport', 'US', 'Reno', 'RNO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Richmond International Airport', 'US', 'Richmond', 'RIC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Sacramento International Airport', 'US', 'Sacramento', 'SMF');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Salt Lake City International Airport', 'US', 'Salt Lake City', 'SLC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'San Antonio International Airport', 'US', 'San Antonio', 'SAT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'San Diego International Airport', 'US', 'San Diego', 'SAN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'San Francisco International Airport', 'US', 'San Francisco', 'SFO');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Norman Y. Mineta San Jose International Airport', 'US', 'San Jose', 'SJC');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'John Wayne Orange County International Airport', 'US', 'Santa Ana', 'SNA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Savannah Hilton Head International Airport', 'US', 'Savannah', 'SAV');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Seattle–Tacoma International Airport', 'US', 'Seattle', 'SEA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'St Louis Lambert International Airport', 'US', 'St Louis', 'STL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Syracuse Hancock International Airport', 'US', 'Syracuse', 'SYR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tampa International Airport', 'US', 'Tampa', 'TPA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tulsa International Airport', 'US', 'Tulsa', 'TUL');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Theodore Francis Green State Airport', 'US', 'Warwick', 'PVD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Ronald Reagan Washington National Airport', 'US', 'Washington', 'DCA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Palm Beach International Airport', 'US', 'West Palm Beach', 'PBI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Carrasco General Cesáreo L. Berisso International Airport', 'UY', 'Ciudad de la Costa', 'MVD');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tashkent International Airport', 'UZ', 'Tashkent', 'TAS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'General José Antonio Anzoategui International Airport', 'VE', 'Barcelona', 'BLA');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Simón Bolívar International Airport', 'VE', 'Caracas', 'CCS');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Noi Bai International Airport', 'VN', 'Hanoi (Soc Son)', 'HAN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Tan Son Nhat International Airport', 'VN', 'Ho Chi Minh City', 'SGN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Bauerfield International Airport', 'VU', 'Port Vila', 'VLI');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Cape Town International Airport', 'ZA', 'Cape Town', 'CPT');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'King Shaka International Airport', 'ZA', 'Durban', 'DUR');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'OR Tambo International Airport', 'ZA', 'Johannesburg', 'JNB');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Kenneth Kaunda International Airport', 'ZM', 'Lusaka', 'LUN');
INSERT INTO public.airport(id, name, iso_country, municipality, iata_code) VALUES (nextval('public.airport_id'), 'Robert Gabriel Mugabe International Airport', 'ZW', 'Harare', 'HRE');
